export const paths = {
  root: () => '/',
  landing: () => '/',
  home: () => '/',
  cart: () => '/cart',
  checkout: () => '/checkout',
  notifications: () => '/notifications',
  profile: () => '/profile',
  settings: () => '/settings',
  shops: () => '/shops',
  shop: (id: string = ':shopId') => `/shops/${id}`,
  specialShop: () => '/special-shop',
  voiceOrder: () => '/voice-order',
  providers: {
    list: () => '/providers',
    detail: (id: string = ':id') => `/providers/${id}`,
  },
  services: {
    catalog: () => '/services',
    requests: () => '/services/requests',
    requestsMine: () => '/services/requests/mine',
    detail: (id: string = ':serviceId') => `/services/${id}`,
    request: () => '/services/request',
  },
  verified: () => '/verified',
  verifiedUsers: {
    list: () => '/verified-users',
    detail: (id: string = ':id') => `/verified-users/${id}`,
  },
  products: {
    list: () => '/products',
    detail: (id: string = ':productId') => `/products/${id}`,
    special: () => '/special-shop',
  },
  orders: {
    root: () => '/orders',
    mine: () => '/orders',
    received: () => '/business/received-orders',
    service: () => '/orders/service',
    detail: (orderId: string = ':id') => `/orders/${orderId}`,
  },
  business: {
    receivedOrders: () => '/business/received-orders',
    manageProducts: () => '/business/manage-products',
  },
  auth: {
    login: () => '/login',
    signup: () => '/signup',
    forgot: () => '/auth/forgot',
    reset: () => '/reset',
  },
  admin: {
    root: () => '/admin',
    login: () => '/admin/login',
    requests: {
      business: () => '/admin/requests/business',
      verification: () => '/admin/requests/verification',
    },
    shops: () => '/admin/shops',
    products: () => '/admin/products',
    announcements: () => '/admin/announcements',
    events: {
      list: () => '/admin/events',
      create: () => '/admin/events/new',
      detail: (id: string = ':id') => `/admin/events/${id}`,
      registrations: (id: string = ':id') => `/admin/events/${id}/registrations`,
    leaderboard: (id: string = ':id') => `/admin/events/${id}/leaderboard`,
    form: (id: string = ':id') => `/admin/events/${id}/form`,
    },
    users: () => '/admin/users',
    analytics: () => '/admin/analytics',
    services: () => '/admin/services',
    serviceRequests: () => '/admin/service-requests',
    formTemplates: () => '/admin/form-templates',
  },
  events: {
    list: () => '/events',
    detail: (eventId: string = ':eventId') => `/events/${eventId}`,
    register: (eventId: string = ':eventId') => `/events/${eventId}/register`,
  },
  verification: {
    requests: () => '/verification-requests',
  },
  manageProducts: () => '/manage-products',
};

export type Paths = typeof paths;
